---

name: bloqit-workflow-application-token-action
description: Obtain a temporary access token for a GitHub Application when running in a GitHub Actions Workflow.

inputs:
  application_private_key:
    description: GitHub Application Private Key value.
    required: true

  application_id:
    description: GitHub Application ID value.
    required: true

outputs:
  token:
    description: A valid token representing the Application that can be used to access what the Application has been scoped to access.

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js

branding:
  icon: lock
  color: green